version: "3"
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile-client
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
  server:
    build: 
      context: .
      dockerfile: Dockerfile-server
    container_name: server
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_NAME=salesDB
      - DB_USERNAME=fasile
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
  db:
    image: postgres:13-alpine
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=fasile
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=salesDB
volumes:
  db-data: